# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 102.8.0esr
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Install Xvfb
      run: |
        sudo apt install xvfb -y
    - name: Enable gradlew executable
      run: chmod +x ./gradlew
    - name: Headless check with Gradle
      run: xvfb-run -a --server-args='-screen 0, 1024x768x24' ./gradlew --stacktrace -Dgeb.env=firefox check
